services:
  club.bookingbundle.left_menu_listener:
    class: Club\BookingBundle\Listener\MenuListener
    arguments: [@router, @security.context, @translator]
    tags:
      - { name: kernel.event_listener, event: top_menu.render, method: onTopMenuRender }
      - { name: kernel.event_listener, event: left_menu.render, method: onLeftMenuRender }
      - { name: kernel.event_listener, event: dash_menu.render, method: onDashMenuRender }
  club.bookingbundle.dashboard_listener:
    class: Club\BookingBundle\Listener\DashboardListener
    arguments: [@service_container]
    tags:
      - { name: kernel.event_listener, event: dashboard.view, method: onDashboardView, priority: 50 }
      - { name: kernel.event_listener, event: member.view, method: onMemberView }
  club.booking.listener.checkin:
    class: Club\BookingBundle\Listener\Checkin
    arguments: [@service_container]
    tags:
      - { name: kernel.event_listener, event: checkin.user, method: onCheckinUser }
  club.booking.listener.shop:
    class: Club\BookingBundle\Listener\Shop
    arguments: [@service_container]
    tags:
      - { name: kernel.event_listener, event: order.paid, method: onOrderPaid }
      - { name: kernel.event_listener, event: order.cancelled, method: onOrderCancelled }
  club.booking.listener.cleanup:
    class: Club\BookingBundle\Listener\CleanupBooking
    arguments: [@service_container]
    tags:
      - { name: kernel.event_listener, event: booking.cleanup, method: onBookingCleanup }
