_field:
  resource: "@ClubBookingBundle/Controller/AdminFieldController.php"
  type: annotation
  prefix: /admin

_interval:
  resource: "@ClubBookingBundle/Controller/AdminIntervalController.php"
  type: annotation
  prefix: /admin

_booking:
  resource: "@ClubBookingBundle/Controller/BookingController.php"
  type: annotation
