services:
    club_booking.interval:
        class: Club\BookingBundle\Helper\Interval
        arguments: [@doctrine.orm.entity_manager]
    club_booking.booking:
        class: Club\BookingBundle\Helper\Booking
        arguments: [@doctrine.orm.entity_manager, @service_container, @security.context, @session, @club_booking.interval, @translator]
