services:
  club.messagebundle.left_menu_render_listener:
    class: Club\MessageBundle\Listener\MenuListener
    arguments: [@router, @security.context, @translator]
    tags:
      - { name: kernel.event_listener, event: left_menu.render, method: onLeftMenuRender }
  club.messagebundle.queue_process_listener:
    class: Club\MessageBundle\Listener\QueueProcessListener
    arguments: [@doctrine.orm.default_entity_manager, @clubmaster_mailer]
    tags:
      - { name: kernel.event_listener, event: message.task, method: onMessageTask }
