services:
  club.eventbundle.listener.top_menu_render_listener:
    class: Club\EventBundle\Listener\MenuListener
    arguments: [@router, @security.context, @translator]
    tags:
      - { name: kernel.event_listener, event: top_menu.render, method: onTopMenuRender }
      - { name: kernel.event_listener, event: left_menu.render, method: onLeftMenuRender }
      - { name: kernel.event_listener, event: dash_menu.render, method: onDashMenuRender }
  club.eventbundle.dashboard_listener:
    class: Club\EventBundle\Listener\DashboardListener
    arguments: [@service_container]
    tags:
      - { name: kernel.event_listener, event: member.view, method: onMemberView }
      - { name: kernel.event_listener, event: dashboard.coming, method: onDashboardComing }
  club.eventbundle.ical_listener:
    class: Club\EventBundle\Listener\IcalListener
    arguments: [@service_container]
    tags:
      - { name: kernel.event_listener, event: user.ical, method: onUserIcal }
