services:
  club.mailbundle.listener.on_password_reset_listener:
    class: Club\MailBundle\Listener\PasswordResetListener
    arguments: [@service_container]
    tags:
      - { name: kernel.event_listener, event: password.reset, method: onPasswordReset }
  club.mailbundle.listener.on_user_new_listener:
    class: Club\MailBundle\Listener\UserNewListener
    arguments: [@service_container]
    tags:
      - { name: kernel.event_listener, event: user.new, method: onUserNew }
  club.mailbundle.listener.on_order_new_listener:
    class: Club\MailBundle\Listener\OrderNewListener
    arguments: [@service_container]
    tags:
      - { name: kernel.event_listener, event: shop.order, method: onShopOrder }
  club.mailbundle.listener.on_order_accepted_listener:
    class: Club\MailBundle\Listener\OrderAcceptedListener
    arguments: [@service_container]
    tags:
      - { name: kernel.event_listener, event: order.change, method: onOrderChange, priority: 10 }
  club.mailbundle.listener.on_mail_task_listener:
    class: Club\MailBundle\Listener\MailSendListener
    arguments: [@doctrine.orm.entity_manager, @mailer, @swiftmailer.transport.real, @clubmaster_mailer, @event_dispatcher]
    tags:
      - { name: kernel.event_listener, event: mail.task, method: onMailTask }
  club.mailbundle.listener.booking_confirm_listener:
    class: Club\MailBundle\Listener\BookingListener
    arguments: [@service_container]
    tags:
      - { name: kernel.event_listener, event: booking.confirm, method: onBookingConfirm }
      - { name: kernel.event_listener, event: booking.cancel, method: onBookingCancel }
  club.mailbundle.listener.exchange:
    class: Club\MailBundle\Listener\ExchangeComment
    arguments: [@service_container]
    tags:
      - { name: kernel.event_listener, event: exchange.comment.new, method: onExchangeCommentNew }
  club.mailbundle.listener.cleanup:
    class: Club\MailBundle\Listener\Cleanup
    arguments: [@service_container]
    tags:
      - { name: kernel.event_listener, event: task.cleanup, method: onTaskCleanup }
