Club\UserBundle\Entity\ProfileAddress:
  type: entity
  table: club_profile_address
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    street: { type: string(255) }
    suburl: { type: string(255) }
    postal_code: { type: string(255) }
    city: { type: string(255) }
    state: { type: string(255) }
    country: { type: string(255) }
    contact_type: { type: string(20), nullable: false }
    is_default: { type: boolean, nullable: false }
  manyToOne:
    profile:
      targetEntity: Profile
  lifecycleCallbacks: {  }
