Club\UserBundle\Entity\Ban:
  type: entity
  table: club_ban
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    user_id: { type: integer, nullable: false } # who has made the ban
    type: { type: string(50), nullable: false }
    value: { type: string(255), nullable: false }
    expire_date: { type: date, nullable: false }
    note: { type: string(1000) }
  lifecycleCallbacks: {  }
