Club\UserBundle\Entity\User:
  type: entity
  table: club_user
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    username: { type: string(255) }
    password: { type: string(255) }
    last_login_time: { type: date, nullable: true }
    last_login_ip: { type: string, string: '100', nullable: true }
    enabled: { type: boolean }
    algorithm: { type: string }
    salt: { type: string }
    locked: { type: boolean }
    expired: { type: boolean }
    expires_at: { type: date, nullable: true }
    created_at: { type: date, nullable: true }
    updated_at: { type: date, nullable: true }
  oneToOne:
    profile:
      targetEntity: Profile
  manyToMany:
    roles:
      targetEntity: Role
  manyToOne:
    language:
      targetEntity: Language
  manyToMany:
    mails:
      targetEntity: Club\MailBundle\Entity\Mail
  lifecycleCallbacks:
    prePersist: [ prePersist ]
