parameters:
    web_path: %kernel.root_dir%/../web
    upload_path: uploads

club_user:
    default_country: DK

club_account_economic:
    enabled: false
    agreement: xxxxxx
    username: xxx
    password: xxxxxxxx
    economic_url: https://www.e-conomic.com/secure/api1/EconomicWebservice.asmx?WSDL
    contraAccount: 5820
    cashbook: Daglig
    currency: DKK

club_payment_cash:
    enabled: true
    controller: club_payment_cash_cash_index

club_payment_quickpay:
    enabled: false
    controller: club_payment_quickpay_quickpay_index
    merchant: 89898978
    secret: 29p61DveBZ79c3144LW61lVz1qrwk2gfAFCxPyi5sn49m3Y3IRK5M6SN5d8a68u7
    protocol: 4
    language: en
    currency: DKK
    autocapture: 1
    #cardtypelock:
    autofee: 0
    quickpay_url: https://secure.quickpay.dk/form/
    testmode: 1

club_api:
    api_key: THIS_IS_A_DEMO_KEY

club_event:
    enabled: true

club_match:
    enabled: true
    google_plus: true
    facebook_like: true
    facebook_api: 485293888165235

club_welcome:
    google_plus: true
    facebook_like: true
    facebook_api: 485293888165235

club_ranking:
    enabled: true
    ranking_top: 5

club_shop:
    view_shop: true
    coupon_account_number: 1010
    guest_account_number: 1010

club_team:
    enabled: true
    future_occurs: 14
    minutes_before_schedule: 120
    minutes_after_schedule: 5
    penalty_enabled: true
    cancel_minute_before: 120
    cancel_minute_created: 5
    num_team_day: 1
    num_team_future: 4
    penalty_product_name: 'Penalty for missed team'
    public_user_activity: true

club_booking:
    enabled: true
    enable_guest: true
    guest_price: 50
    num_book_guest_day: 2
    num_book_guest_future: 2
    num_book_same_partner_day: 2
    num_book_same_partner_future: 2
    num_book_day: 2
    num_book_future: 2
    days_book_future: 6
    days_book_future_entire_day: true
    cancel_minute_before: 120
    cancel_minute_created: 5
    booking_style: horizontal
    cancel_without_checkin: false
    confirm_minutes_before: 120
    confirm_minutes_after: 5
    public_user_activity: true

club_mail:
    default_sender_address: info@clubmaster.org
    default_sender_name: ClubMaster Administrator
    mail_on_welcome: true
    mail_on_booking: true
    mail_on_order: true

club_feedback:
    enabled: true

club_exchange:
    enabled: true

club_news:
    enabled: true

club_checkin:
    allowed_ip:
        - 127.0.0.1
        - ::1

club_layout:
    title: ClubMaster

club_weather:
    enabled: true
    key: fdeb1d24d8174537121809
    longtitude: 9.917771
    latitude: 57.028811

club_tournament:
    enabled: true

club_facebook:
    enabled: false
    app_id: ~
