parameters:
    web_path: %kernel.root_dir%/../web
    upload_path: uploads

club_api:
    api_key: THIS_IS_A_DEMO_KEY

club_team:
    future_occurs: 25
    minutes_before_schedule: 120
    penalty_enabled: true
    cancel_minute_before: 120
    cancel_minute_created: 5
    num_team_day: 1
    num_team_future: 4

club_booking:
    enable_guest: true
    num_book_guest_day: 1
    num_book_guest_future: 1
    num_book_same_partner_day: 1
    num_book_same_partner_future: 1
    num_book_day: 1
    num_book_future: 4
    cancel_minute_before: 120
    cancel_minute_created: 5

ornicar_gravatar:
    rating: g
    size: 160
    default: mm
