_security_login:
    pattern:  /login
    defaults: { _controller: ClubUserBundle:Auth:login }

_security_check:
    pattern:  /login_check

_security_logout:
    pattern:  /logout

homepage:
  pattern: /
  defaults: { _controller: ClubUserBundle:User:index }

_user:
  resource: "@ClubUserBundle/Controller/UserController.php"
  type: annotation

_group:
  resource: "@ClubUserBundle/Controller/GroupController.php"
  type: annotation

_location:
  resource: "@ClubUserBundle/Controller/LocationController.php"
  type: annotation

_role:
  resource: "@ClubUserBundle/Controller/RoleController.php"
  type: annotation

_auth:
  resource: "@ClubUserBundle/Controller/AuthController.php"
  type: annotation

_rest:
  resource: "@ClubRestBundle/Controller/DefaultController.php"
  type: annotation
  prefix: /rest
