ClubPasskeyBundle:
    resource: "@ClubPasskeyBundle/Controller/"
    type:     annotation
    prefix:   /

ClubCheckinBundle:
    resource: "@ClubCheckinBundle/Controller/"
    type:     annotation
    prefix:   /

ClubPaymentCashBundle:
    resource: "@ClubPaymentCashBundle/Controller/"
    type:     annotation
    prefix:   /payment/

ClubPaymentQuickpayBundle:
    resource: "@ClubPaymentQuickpayBundle/Controller/"
    type:     annotation
    prefix:   /payment/

ClubAPIBundle:
    resource: "@ClubAPIBundle/Controller/"
    type: annotation
    prefix: /api/

ClubTeamBundle:
    resource: "@ClubTeamBundle/Resources/config/routing.yml"

ClubShopBundle:
    resource: "@ClubShopBundle/Resources/config/routing.yml"

ClubUserBundle:
    resource: "@ClubUserBundle/Resources/config/routing.yml"

ClubTaskBundle:
    resource: "@ClubTaskBundle/Controller/"
    type:     annotation

ClubMailBundle:
    resource: "@ClubMailBundle/Controller/"

ClubLogBundle:
    resource: "@ClubLogBundle/Resources/config/routing.yml"

ClubEventBundle:
    resource: "@ClubEventBundle/Resources/config/routing.yml"

ClubInstallBundle:
    resource: "@ClubInstallerBundle/Resources/config/routing.yml"
    prefix: /installer

ClubConfiguratorBundle:
    resource: "@ClubConfiguratorBundle/Resources/config/routing/webconfigurator.xml"
    prefix: /configurator

ClubMessageBundle:
    resource: "@ClubMessageBundle/Resources/config/routing.yml"

ClubBookingBundle:
    resource: "@ClubBookingBundle/Resources/config/routing.yml"

ClubDashboardBundle:
    resource: "@ClubDashboardBundle/Resources/config/routing.yml"

ClubWelcomeBundle:
    resource: "@ClubWelcomeBundle/Resources/config/routing.yml"

ClubFeedbackBundle:
    resource: "@ClubFeedbackBundle/Resources/config/routing.yml"

ClubMatchBundle:
    resource: "@ClubMatchBundle/Controller/"

homepage:
    pattern: /
    defaults: { _controller: ClubWelcomeBundle:Welcome:index }
