homepage:
  pattern: /
  defaults: { _controller: ClubDashboardBundle:AdminDashboard:index }

_api:
  resource: "@ClubAPIBundle/Resources/config/routing.yml"

_shop:
  resource: "@ClubShopBundle/Resources/config/routing.yml"

_user:
  resource: "@ClubUserBundle/Resources/config/routing.yml"

_account:
  resource: "@ClubAccountBundle/Resources/config/routing.yml"

_task:
  resource: "@ClubTaskBundle/Resources/config/routing.yml"

_mail:
  resource: "@ClubMailBundle/Resources/config/routing.yml"

_log:
  resource: "@ClubLogBundle/Resources/config/routing.yml"

_event:
  resource: "@ClubEventBundle/Resources/config/routing.yml"

_installer:
  resource: "@ClubInstallerBundle/Resources/config/routing.yml"

_feedback:
  resource: "@ClubFeedbackBundle/Resources/config/routing.yml"

_message:
  resource: "@ClubMessageBundle/Resources/config/routing.yml"

_dashboard:
  resource: "@ClubDashboardBundle/Resources/config/routing.yml"
