security:
    encoders:
        Club\UserBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    providers:
        main:
          entity: { class: Club\UserBundle\Entity\User, property: username }

    firewalls:
        profiler:
          pattern: ^/_profiler.*
          security: false
        wdt:
          pattern: ^/_wdt
          security: false
        main:
            form_login:
                check_path: /login_check
                login_path: /login
            logout: true
            security: true
            anonymous: true
    access_control:
        - { path: /login.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /.*, role: ROLE_ADMIN }
