security:
    encoders:
        Club\UserBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    role_hierarchy:
      ROLE_ADMIN: ROLE_USER

    providers:
        main:
          entity: { class: Club\UserBundle\Entity\User, property: member_number }

    firewalls:
        profiler:
          pattern: ^/_profiler.*
          security: false
        wdt:
          pattern: ^/_wdt
          security: false
        main:
            form_login:
                check_path: /login_check
                login_path: /login
                failure_handler: failure.password.handler
                success_handler: success.password.handler
            logout: true
            security: true
            anonymous: true

    access_control:
        - { path: /login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /auth/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /rest.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /installer.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /event/ical, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /.*, roles: 'ROLE_USER' }
        - { path: /admin/.*, roles: 'ROLE_ADMIN' }
