services:
  club.logbundle.listener.on_shop_order_listener:
    class: Club\LogBundle\Listener\NewOrderListener
    arguments: [@doctrine.orm.entity_manager,@security.context]
    tags:
      - { name: kernel.event_listener, event: shop.order, method: onShopOrder }
  club.logbundle.listener.on_order_change_listener:
    class: Club\LogBundle\Listener\OrderChangeListener
    arguments: [@doctrine.orm.entity_manager,@security.context]
    tags:
      - { name: kernel.event_listener, event: order.change, method: onOrderChange }
  club.logbundle.listener.on_event_add_listener:
    class: Club\LogBundle\Listener\AddEventListener
    arguments: [@doctrine.orm.entity_manager,@security.context]
    tags:
      - { name: kernel.event_listener, event: event.add, method: onEventAdd }
  club.logbundle.listener.on_event_attend_listener:
    class: Club\LogBundle\Listener\AttendEventListener
    arguments: [@doctrine.orm.entity_manager,@security.context]
    tags:
      - { name: kernel.event_listener, event: event.attend, method: onEventAttend }
  club.logbundle.listener.on_event_unattend_listener:
    class: Club\LogBundle\Listener\UnattendEventListener
    arguments: [@doctrine.orm.entity_manager,@security.context]
    tags:
      - { name: kernel.event_listener, event: event.unattend, method: onEventUnattend }
  club.logbundle.listener.cleanup_log_listener:
    class: Club\LogBundle\Listener\CleanupLogListener
    arguments: [@doctrine.orm.entity_manager,@security.context]
    tags:
      - { name: kernel.event_listener, event: log.task, method: onLogTask }
  club.logbundle.listener.log_listener:
    class: Club\LogBundle\Listener\LogListener
    arguments: [@doctrine.orm.entity_manager,@security.context]
    tags:
      - { name: kernel.event_listener, event: connection.error, method: onConnectionError }
