services:
  club_layout_twig_currency_extension:
    class: Club\FormExtraBundle\Twig\CurrencyExtension
    arguments: [@service_container]
    tags:
      - { name: twig.extension }
  club_layout_twig_date_extension:
    class: Club\FormExtraBundle\Twig\DateExtension
    arguments: [@service_container]
    tags:
      - { name: twig.extension }
  club_layout_twig_application_extension:
    class: Club\FormExtraBundle\Twig\ApplicationExtension
    arguments: [@service_container]
    tags:
      - { name: twig.extension }
