services:
  club.shopbundle.listener.on_shop_order_listener:
    class: Club\ShopBundle\Listener\NewOrderListener
    arguments: [@doctrine.orm.entity_manager]
    tags:
      - { name: kernel.event_listener, event: shop.order, method: onShopOrder }
  club.shopbundle.listener.new_subscription_listener:
    class: Club\ShopBundle\Listener\NewSubscriptionListener
    arguments: [@doctrine.orm.entity_manager]
    tags:
      - { name: kernel.event_listener, event: order.change, method: onOrderChange, priority: 10 }
  club.shopbundle.listener.on_order_change_listener:
    class: Club\ShopBundle\Listener\OrderChangeListener
    arguments: [@doctrine.orm.entity_manager]
    tags:
      - { name: kernel.event_listener, event: order.change, method: onOrderChange, priority: 5 }
  club.shopbundle.listener.auto_renewal.listener:
    class: Club\ShopBundle\Listener\AutoRenewalListener
    arguments: [@doctrine.orm.entity_manager,@order]
    tags:
      - { name: kernel.event_listener, event: auto_renewal.task, method: onAutoRenewalTask }
  club.shopbundle.listener.subscription_use_listener:
    class: Club\ShopBundle\Listener\SubscriptionUseListener
    arguments: [@doctrine.orm.entity_manager,@security.context]
    tags:
      - { name: kernel.event_listener, event: team.attend, method: onSubscriptionUse }
