services:
  cart:
    class: Club\ShopBundle\Helper\Cart
    arguments: [@doctrine.orm.default_entity_manager,@session,@security.context,@club_user.location]
  order:
    class: Club\ShopBundle\Helper\Order
    arguments: [@service_container]
  subscription:
    class: Club\ShopBundle\Helper\Subscription
    arguments: [@doctrine.orm.default_entity_manager,@session,@translator]
  club_shop.product:
    class: Club\ShopBundle\Helper\Product
    arguments: [@doctrine.orm.default_entity_manager]
  twig.extension.text:
    class: Twig_Extensions_Extension_Text
    tags:
      - { name: twig.extension }
  shop_paymentmethod:
    class: Club\ShopBundle\Helper\PaymentMethod
    arguments: [@event_dispatcher]
