_api_auth:
  resource: "@ClubAPIBundle/Controller/AuthController.php"
  type: annotation
  prefix: /api

_api_event:
  resource: "@ClubAPIBundle/Controller/EventController.php"
  type: annotation
  prefix: /api/events

_api_team:
  resource: "@ClubAPIBundle/Controller/TeamController.php"
  type: annotation
  prefix: /api/teams

_api_user:
  resource: "@ClubAPIBundle/Controller/UserController.php"
  type: annotation
  prefix: /api/users

_api_booking:
  resource: "@ClubAPIBundle/Controller/BookingController.php"
  type: annotation
  prefix: /api/booking

_api_location:
  resource: "@ClubAPIBundle/Controller/LocationController.php"
  type: annotation
  prefix: /api/locations

_api_field:
  resource: "@ClubAPIBundle/Controller/FieldController.php"
  type: annotation
  prefix: /api/fields

