services:
    club_layout_form_extension:
        class: Club\LayoutBundle\Form\HelpTypeExtension
        tags:
            - { name: "form.type_extension", alias: "field" }
    club_layout_form_tinymce:
        class: Club\LayoutBundle\Form\TinyMceType
        tags:
            - { name: "form.type", alias: "tinymce" }
    club_layout_form_jquery_calendar:
        class: Club\LayoutBundle\Form\JQueryDateTimeType
        tags:
            - { name: "form.type", alias: "jquery_datetime" }
    club_layout_form_jquery_date:
        class: Club\LayoutBundle\Form\JQueryDateType
        tags:
            - { name: "form.type", alias: "jquery_date" }
    club_layout_form_jquery_birthday:
        class: Club\LayoutBundle\Form\JQueryBirthdayType
        tags:
            - { name: "form.type", alias: "jquery_birthday" }
    club_layout_form_jquery_autocomplete:
        class: Club\LayoutBundle\Form\JQueryAutocompleteType
        arguments: [@doctrine.orm.entity_manager, @translator]
        tags:
            - { name: "form.type", alias: "jquery_autocomplete" }
    club_layout_form_gender:
        class: Club\LayoutBundle\Form\GenderType
        arguments: [@translator]
        tags:
            - { name: "form.type", alias: "gender" }
    club_layout_form_best_of_set:
        class: Club\LayoutBundle\Form\BestOfSetType
        tags:
            - { name: "form.type", alias: "best_of_set" }
