services:
  club.accountbundle.listener.on_shop_order_listener:
    class: Club\AccountBundle\Listener\NewTransactionListener
    arguments: [@doctrine.orm.entity_manager]
    tags:
      - { name: kernel.listener, event: onShopOrder }
