services:
  club.userbundle.listener.group.recalc:
    class: Club\UserBundle\Listener\GroupRecalcListener
    arguments: [@doctrine.orm.entity_manager,@security.context]
    tags:
      - { name: kernel.event_listener, event: group.task, method: onGroupTask }
      - { name: kernel.event_listener, event: group.edit, method: onGroupEdit }
  club.userbundle.listener.login_attempt.listener:
    class: Club\UserBundle\Listener\CleanupLoginAttemptListener
    arguments: [@doctrine.orm.entity_manager]
    tags:
      - { name: kernel.event_listener, event: login_attempt.task, method: onLoginAttemptTask }
  club.userbundle.listener.ban.listener:
    class: Club\UserBundle\Listener\CleanupBanListener
    arguments: [@doctrine.orm.entity_manager]
    tags:
      - { name: kernel.event_listener, event: ban.task, method: onBanTask }
  club.userbundle.login_listener:
    class: Club\UserBundle\Listener\LoginListener
    arguments: [@doctrine.orm.entity_manager, @security.context, @session]
    tags:
      - { name: kernel.event_listener, event: security.interactive_login }
  club.userbundle.location:
    class: Club\UserBundle\Listener\LocationListener
    arguments: [@service_container]
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
  club.userbundle.top_menu_listener:
    class: Club\UserBundle\Listener\MenuListener
    arguments: [@router, @security.context, @translator]
    tags:
      - { name: kernel.event_listener, event: top_menu.render, method: onTopMenuRender }
  club.userbundle.left_menu_listener:
    class: Club\UserBundle\Listener\MenuListener
    arguments: [@router, @security.context, @translator]
    tags:
      - { name: kernel.event_listener, event: left_menu.render, method: onLeftMenuRender }
  club.user.dashboard_listener:
    class: Club\UserBundle\Listener\DashboardListener
    arguments: [@doctrine.orm.entity_manager, @security.context, @templating]
    tags:
      - { name: kernel.event_listener, event: admin_dashboard.view, method: onAdminDashboardView }
  club.user.fixtures.load:
    class: Club\UserBundle\Fixtures\Load
    arguments: [@doctrine.orm.entity_manager]
    tags:
      - { name: kernel.event_listener, event: fixtures.init, method: onFixturesInit }
