services:
  club.userbundle.listener.request:
    class: Club\UserBundle\Listener\RequestListener
    arguments: [@doctrine.orm.entity_manager,@security.context,@session]
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
  club.userbundle.listener.group.recalc:
    class: Club\UserBundle\Listener\GroupRecalcListener
    arguments: [@doctrine.orm.entity_manager,@security.context]
    tags:
      - { name: kernel.event_listener, event: group.task, method: onGroupTask }
  club.userbundle.listener.login_attempt.listener:
    class: Club\UserBundle\Listener\CleanupLoginAttemptListener
    arguments: [@doctrine.orm.entity_manager]
    tags:
      - { name: kernel.event_listener, event: login_attempt.task, method: onLoginAttemptTask }
  club.userbundle.listener.ban.listener:
    class: Club\UserBundle\Listener\CleanupBanListener
    arguments: [@doctrine.orm.entity_manager]
    tags:
      - { name: kernel.event_listener, event: ban.task, method: onBanTask }
  club.userbundle.login_listener:
    class: Club\UserBundle\Listener\LoginListener
    arguments: [@doctrine.orm.entity_manager,@security.context]
    tags:
      - { name: kernel.event_listener, event: security.interactive_login }
