_security_login:
    pattern:  /login
    defaults: { _controller: ClubUserBundle:Auth:login }

_security_check:
    pattern:  /login_check

_security_logout:
    pattern:  /logout

_user:
  resource: "@ClubUserBundle/Controller/UserController.php"
  type: annotation

_auth:
  resource: "@ClubUserBundle/Controller/AuthController.php"
  type: annotation

_group:
  resource: "@ClubUserBundle/Controller/GroupController.php"
  type: annotation
  prefix: /admin

_location:
  resource: "@ClubUserBundle/Controller/LocationController.php"
  type: annotation
  prefix: /admin

_role:
  resource: "@ClubUserBundle/Controller/RoleController.php"
  type: annotation
  prefix: /admin

_ban:
  resource: "@ClubUserBundle/Controller/BanController.php"
  type: annotation
  prefix: /admin

_config:
  resource: "@ClubUserBundle/Controller/ConfigController.php"
  type: annotation
  prefix: /admin

_currency:
  resource: "@ClubUserBundle/Controller/CurrencyController.php"
  type: annotation
  prefix: /admin

_language:
  resource: "@ClubUserBundle/Controller/LanguageController.php"
  type: annotation
  prefix: /admin
