login_check:
  pattern:  /login_check

logout:
  pattern:  /logout

_auth:
  resource: "@ClubUserBundle/Controller/AuthController.php"
  type: annotation

_user:
  resource: "@ClubUserBundle/Controller/UserController.php"
  type: annotation

_location:
  resource: "@ClubUserBundle/Controller/LocationController.php"
  type: annotation

_admin_user:
  resource: "@ClubUserBundle/Controller/AdminUserController.php"
  type: annotation
  prefix: /admin

_user_note:
  resource: "@ClubUserBundle/Controller/UserNoteController.php"
  type: annotation
  prefix: /admin

_group:
  resource: "@ClubUserBundle/Controller/GroupController.php"
  type: annotation
  prefix: /admin

_admin_location:
  resource: "@ClubUserBundle/Controller/AdminLocationController.php"
  type: annotation
  prefix: /admin

_admin_location_config:
  resource: "@ClubUserBundle/Controller/AdminLocationConfigController.php"
  type: annotation
  prefix: /admin

_ban:
  resource: "@ClubUserBundle/Controller/BanController.php"
  type: annotation
  prefix: /admin

_config:
  resource: "@ClubUserBundle/Controller/ConfigController.php"
  type: annotation
  prefix: /admin

_currency:
  resource: "@ClubUserBundle/Controller/CurrencyController.php"
  type: annotation
  prefix: /admin

_filter:
  resource: "@ClubUserBundle/Controller/FilterController.php"
  type: annotation
  prefix: /admin

_login_log:
  resource: "@ClubUserBundle/Controller/LoginLogController.php"
  type: annotation
  prefix: /admin
