services:
    failure.password.handler:
        class: Club\UserBundle\Helper\FailurePasswordHandler
        arguments: [@doctrine.orm.entity_manager]
    success.login.handler:
        class: Club\UserBundle\Helper\SuccessLoginHandler
        arguments: [@router, @security.context]
    clubmaster.version:
        class: Club\UserBundle\Helper\Version
    clubmaster.ban:
        class: Club\UserBundle\Helper\Ban
        arguments: [@doctrine.orm.entity_manager, @security.context]
    clubmaster.user:
        class: Club\UserBundle\Helper\User
        arguments: [@service_container]
    club_user.reset_password:
        class: Club\UserBundle\Helper\ResetPassword
        arguments: [@doctrine.orm.entity_manager]
    club_user.application:
        class: Club\UserBundle\Helper\Application
        arguments: [@service_container]
    club_user.currency:
        class: Club\UserBundle\Helper\Currency
        arguments: [@doctrine.orm.entity_manager, @session, @club_user.location]
    club_user.location:
        class: Club\UserBundle\Helper\Location
        arguments: [@doctrine.orm.entity_manager, @session, @logger]
